[General]
# This file contains the mavlink-router configuration

# Disable TCP port
TcpServerPort = 0

[UartEndpoint fc_uart]
Device = /dev/ttyS2
Baud = 921600
FlowControl = false

[UdpEndpoint GCS]
Mode = Server
Address = 0.0.0.0
Port = 14550

[UdpEndpoint pc_endpoint]
Mode = Normal
Address = 192.168.0.29
Port = 14571

[UdpEndpoint LocalMavProxy]
Mode = Normal
Address = 127.0.0.1
Port = 14571
